# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain_tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('zone', models.CharField(max_length=20, verbose_name='\u0417\u043e\u043d\u0430 1 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0443\u0440\u043e\u0432\u043d\u044f')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u0434\u043e\u043c\u0435\u043d \u0432 \u0433\u043e\u0434')),
                ('active', models.BooleanField(verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0439')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date_inactive', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'rhcp_domain_tariff',
                'verbose_name': '\u0422\u0430\u0440\u0438\u0444 \u0434\u043e\u043c\u0435\u043d\u0430',
                'verbose_name_plural': '\u0422\u0430\u0440\u0438\u0444\u044b \u0434\u043e\u043c\u0435\u043d\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='site_tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('space', models.IntegerField(verbose_name='\u0414\u0438\u0441\u043a\u043e\u0432\u043e\u0435 \u043f\u0440\u043e\u0441\u0442\u0440\u0430\u043d\u0441\u0442\u0432\u043e')),
                ('support', models.BooleanField(verbose_name='\u0422\u0435\u0445\u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\u0435\u0441\u044f\u0446')),
                ('year_discount', models.IntegerField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u043f\u0440\u0438 \u043e\u043f\u043b\u0430\u0442\u0435 \u0437\u0430 \u0433\u043e\u0434, %')),
                ('active', models.BooleanField(verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0439')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date_inactive', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'rhcp_site_tariff',
                'verbose_name': '\u0422\u0430\u0440\u0438\u0444 \u0441\u0430\u0439\u0442\u0430',
                'verbose_name_plural': '\u0422\u0430\u0440\u0438\u0444\u044b \u0441\u0430\u0439\u0442\u043e\u0432',
            },
        ),
    ]
