# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0009_auto_20160610_0656'),
        ('rhcp_core', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhcp_client.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhcp_core.site')),
            ],
            options={
                'db_table': 'rhcp_client_site',
                'verbose_name': '\u0421\u0430\u0439\u0442 \u043a\u043b\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u0421\u0430\u0439\u0442\u044b \u043a\u043b\u0438\u0435\u043d\u0442\u043e\u0432',
            },
        ),
    ]
