# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0009_auto_20160610_0656'),
        ('rhcp_core', '0003_client_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_site',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client_site',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rhcp_client.client'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='client_site',
        ),
    ]
