# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_core', '0004_auto_20160610_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='active',
        ),
    ]
