# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='man_info',
            options={'ordering': ['rus_name'], 'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0444\u0438\u0437\u0438\u0447\u0435\u0441\u043a\u043e\u0433\u043e \u043b\u0438\u0446\u0430', 'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0444\u0438\u0437\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u043b\u0438\u0446'},
        ),
        migrations.RemoveField(
            model_name='man_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='man_info',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='man_info',
            name='third_name',
        ),
        migrations.AddField(
            model_name='man_info',
            name='rus_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u0424\u0418\u041e \u043f\u043e-\u0440\u0443\u0441\u0441\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='man_info',
            name='eng_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u0424\u0418\u041e \u043f\u043e-\u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438'),
        ),
    ]
