# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0002_auto_20160609_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man_info',
            name='phones',
            field=models.TextField(default='', max_length=100, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
    ]
