# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0003_auto_20160609_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ind_info',
            options={'ordering': ['rus_name'], 'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0438\u043d\u0434\u0438\u0432\u0438\u0434\u0443\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0442\u0435\u043b\u044f', 'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0438\u043d\u0434\u0438\u0432\u0438\u0434\u0443\u0430\u043b\u044c\u043d\u044b\u0445 \u043f\u0440\u0435\u0434\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0442\u0435\u043b\u0435\u0439'},
        ),
        migrations.AlterModelOptions(
            name='org_info',
            options={'ordering': ['rus_name'], 'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438', 'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0439'},
        ),
        migrations.RemoveField(
            model_name='ind_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ind_info',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='ind_info',
            name='third_name',
        ),
        migrations.RemoveField(
            model_name='org_info',
            name='caption',
        ),
        migrations.AddField(
            model_name='ind_info',
            name='date_born',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='emails',
            field=models.TextField(default='', max_length=500, verbose_name='\u0415\u043c\u0430\u0439\u043b\u044b'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='eng_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e-\u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='faxes',
            field=models.TextField(default='', max_length=500, verbose_name='\u0424\u0430\u043a\u0441\u044b'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='inn',
            field=models.CharField(default='', max_length=12, verbose_name='\u0418\u041d\u041d'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='passport',
            field=models.CharField(default='', max_length=150, verbose_name='\u041f\u0430\u0441\u043f\u043e\u0440\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='phones',
            field=models.TextField(default='', max_length=500, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='post_address',
            field=models.CharField(default='', max_length=250, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='resident',
            field=models.BooleanField(default=True, verbose_name='\u0420\u0435\u0437\u0438\u0434\u0435\u043d\u0442 \u0420\u0424'),
        ),
        migrations.AddField(
            model_name='ind_info',
            name='rus_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e-\u0440\u0443\u0441\u0441\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='bank',
            field=models.CharField(default='', max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u043d\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='bik',
            field=models.CharField(default='', max_length=150, verbose_name='\u0411\u0418\u041a'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='chief_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u0424\u0418\u041e \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='date_born',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='emails',
            field=models.TextField(default='', max_length=500, verbose_name='\u0415\u043c\u0430\u0439\u043b\u044b'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='eng_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e-\u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='faxes',
            field=models.TextField(default='', max_length=500, verbose_name='\u0424\u0430\u043a\u0441\u044b'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='inn',
            field=models.CharField(default='', max_length=12, verbose_name='\u0418\u041d\u041d'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='jur_address',
            field=models.CharField(default='', max_length=250, verbose_name='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='kpp',
            field=models.CharField(default='', max_length=12, verbose_name='\u041a\u041f\u041f'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='ks',
            field=models.CharField(default='', max_length=20, verbose_name='\u041a\u043e\u0440\u0440\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0441\u043a\u0438\u0439 \u0441\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='ogrn',
            field=models.CharField(default='', max_length=12, verbose_name='\u041e\u0413\u0420\u041d'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='passport',
            field=models.CharField(default='', max_length=150, verbose_name='\u041f\u0430\u0441\u043f\u043e\u0440\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='phones',
            field=models.TextField(default='', max_length=500, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='post_address',
            field=models.CharField(default='', max_length=250, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='resident',
            field=models.BooleanField(default=True, verbose_name='\u0420\u0435\u0437\u0438\u0434\u0435\u043d\u0442 \u0420\u0424'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='rs',
            field=models.CharField(default='', max_length=20, verbose_name='\u0420\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='rus_name',
            field=models.CharField(default='', max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e-\u0440\u0443\u0441\u0441\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='man_info',
            name='emails',
            field=models.TextField(default='', max_length=500, verbose_name='\u0415\u043c\u0430\u0439\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='man_info',
            name='faxes',
            field=models.TextField(default='', max_length=500, verbose_name='\u0424\u0430\u043a\u0441\u044b'),
        ),
        migrations.AlterField(
            model_name='man_info',
            name='phones',
            field=models.TextField(default='', max_length=500, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
    ]
