# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0004_auto_20160609_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_info',
            name='date_born',
        ),
        migrations.RemoveField(
            model_name='org_info',
            name='passport',
        ),
    ]
