# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0005_auto_20160609_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind_info',
            name='client',
        ),
        migrations.RemoveField(
            model_name='man_info',
            name='client',
        ),
        migrations.RemoveField(
            model_name='org_info',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u043d\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='bik',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0411\u0418\u041a'),
        ),
        migrations.AddField(
            model_name='client',
            name='chief_name',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044f \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_born',
            field=models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='emails',
            field=models.TextField(max_length=500, null=True, verbose_name='\u0415\u043c\u0430\u0439\u043b\u044b'),
        ),
        migrations.AddField(
            model_name='client',
            name='eng_name',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0438\u043b\u0438 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e-\u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='client',
            name='faxes',
            field=models.TextField(max_length=500, null=True, verbose_name='\u0424\u0430\u043a\u0441\u044b'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=12, null=True, verbose_name='\u0418\u041d\u041d'),
        ),
        migrations.AddField(
            model_name='client',
            name='jur_address',
            field=models.CharField(max_length=250, null=True, verbose_name='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='client',
            name='kpp',
            field=models.CharField(max_length=12, null=True, verbose_name='\u041a\u041f\u041f'),
        ),
        migrations.AddField(
            model_name='client',
            name='ks',
            field=models.CharField(max_length=20, null=True, verbose_name='\u041a\u043e\u0440\u0440\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0441\u043a\u0438\u0439 \u0441\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='client',
            name='ogrn',
            field=models.CharField(max_length=12, null=True, verbose_name='\u041e\u0413\u0420\u041d'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=150, null=True, verbose_name='\u041f\u0430\u0441\u043f\u043e\u0440\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='phones',
            field=models.TextField(max_length=500, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
        migrations.AddField(
            model_name='client',
            name='post_address',
            field=models.CharField(max_length=250, null=True, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='client',
            name='resident',
            field=models.BooleanField(default=True, verbose_name='\u0420\u0435\u0437\u0438\u0434\u0435\u043d\u0442 \u0420\u0424'),
        ),
        migrations.AddField(
            model_name='client',
            name='rs',
            field=models.CharField(max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442'),
        ),
        migrations.AddField(
            model_name='client',
            name='rus_name',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0438\u043b\u0438 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e-\u0440\u0443\u0441\u0441\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_add',
            field=models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u044b RHCP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u044b RHCP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u0441\u0438\u0441\u0442\u0435\u043c\u044b RHCP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nic_hdl',
            field=models.CharField(max_length=50, null=True, verbose_name='Nic-hdl \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430 \u0434\u043e\u043c\u0435\u043d\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=50, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c \u043f\u043e\u0440\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u044b RHCP'),
        ),
        migrations.DeleteModel(
            name='ind_info',
        ),
        migrations.DeleteModel(
            name='man_info',
        ),
        migrations.DeleteModel(
            name='org_info',
        ),
    ]
