# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0009_auto_20160610_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_last',
            field=models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0432\u0445\u043e\u0434\u0430 \u0432 \u0441\u0438\u0441\u0442\u0435\u043c\u0443 RHCP'),
        ),
    ]
