# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcp_client', '0011_auto_20160610_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bik',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u0411\u0418\u041a'),
        ),
        migrations.AlterField(
            model_name='client',
            name='chief_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u0424\u0418\u041e \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044f \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_last',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0432\u0445\u043e\u0434\u0430 \u0432 \u0441\u0438\u0441\u0442\u0435\u043c\u0443 RHCP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='\u0418\u041d\u041d'),
        ),
        migrations.AlterField(
            model_name='client',
            name='jur_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='\u041a\u041f\u041f'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ks',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043e\u0440\u0440\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0441\u043a\u0438\u0439 \u0441\u0447\u0451\u0442'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='\u041e\u0413\u0420\u041d'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0420\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442'),
        ),
    ]
